GameStoreWeb/Controllers/CommentController.cs
using GameStoreData.Identity.Data;
using GameStoreData.Models;
using GameStoreData.Service;
using GameStoreData.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace GameStoreWeb.Controllers
{
    public class CommentController : Controller
    {
        private readonly IGameService _service;
        private readonly UserManager<ApplicationUser> _userManager;

        public CommentController(IGameService service, UserManager<ApplicationUser> userManager)
        {
            _service = service;
            _userManager = userManager;
        }

        public async Task<IActionResult> ReplyToComment(int id)
        {
            var comment = await _service.GetCommentByIdAsync(id);
            var game = await _service.GetGameByIdAsync(comment.GameId);

            game.CommentVM = new CommentVM
            {
                GameId = game.Id,
                ParentCommentId = id
            };

            return View("Views/Game/Details.cshtml", game);
        }

        public async Task<IActionResult> AddComment(CommentVM commentVM)
        {
            if (commentVM.CommentVMId != 0)
            {
                await _service.UpdateCommentAsync(commentVM);
            }
            else
            {
                await _service.AddCommentAsync(commentVM, _userManager.GetUserId(User));
            }
            return RedirectToAction("Details", "Game", new { id = commentVM.GameId });
        }

        public async Task<IActionResult> ChangeCommentState(int id)
        {
            var comment = await _service.GetCommentByIdAsync(id);
            await _service.ChangeCommentStateAsync(comment);

            TempData["IsRedirected"] = true;
            return RedirectToAction("Details", "Game", new { id = comment.GameId });
        }

        [HttpGet]
        public async Task<IActionResult> UpdateComment(int id)
        {
            var comment = await _service.GetCommentByIdAsync(id);
            var game = await _service.GetGameByIdAsync(comment.GameId);

            game.CommentVM = new CommentVM
            {
                CommentVMId = comment.Id,
                Body = comment.Body,
                GameId = game.Id
            };

            return View("Views/Game/Details.cshtml", game);
        }
    }
}

GameStoreWeb/Controllers/GameController.cs
using GameStoreData.Models;
using GameStoreData.Service;
using GameStoreData.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace GameStoreWeb.Controllers
{
    public class GameController : Controller
    {
        private readonly IGameService _service;

        public GameController(IGameService service)
        {
            _service = service;
        }

        public IActionResult Index()
        {
            return RedirectToAction("ListGames");
        }

        [HttpGet("Create")]
        [Authorize(Roles = "Admin, Manager")]
        public async Task<IActionResult> Create()
        {
            var game = new Game();
            var gameVM = await _service.CreateGameVMAsync(game);

            return View(gameVM);
        }

        [HttpPost("Create")]
        public async Task<IActionResult> Create(GameVM gameVM)
        {
            var game = await _service.CreateGameAsync(gameVM);
            await _service.CreateNewGameAsync(game);

            return RedirectToAction("ListGames");
        }

        [HttpGet("Games")]
        public async Task<IActionResult> ListGames()
        {
            var gameVM = new GameVM();
            gameVM.Games = await _service.GetGamesAsync();

            var genres = await _service.GetGenresAsync();
            _service.InitializeGenresList(gameVM, genres);
            gameVM.SelectedGenreIds = genres.Select(g => g.Id).ToList();

            return View(gameVM);
        }

        [HttpGet("Update/{id}")]
        [Authorize(Roles = "Admin, Manager")]
        public async Task<IActionResult> Edit(int id)
        {
            var game = await _service.GetGameByIdAsync(id);
            var gameVM = await _service.CreateGameVMAsync(game);

            return View(gameVM);
        }

        [HttpPost]
        public async Task<IActionResult> Update(GameVM gameVM)
        {
            var game = await _service.CreateGameAsync(gameVM);
            await _service.UpdateGameAsync(game);

            return RedirectToAction("ListGames");
        }

        [Authorize(Roles = "Admin, Manager")]
        public async Task<IActionResult> Delete(int id)
        {
            await _service.DeleteGameAsync(id);
            return RedirectToAction("ListGames");
        }

        [HttpGet("Details/{id}")]
        public async Task<IActionResult> Details(int id)
        {
            TempData.TryGetValue("IsRedirected", out var isRedirected);
            var game = await _service.GetGameAndDeleteInactiveComments((bool?)isRedirected ?? false, id);
            TempData["IsRedirected"] = false;

            return View(game);
        }

        public async Task<IActionResult> FilterGames(GameVM gameVM)
        {
            var gameList = await _service.GetGamesWithSelectedGenresAsync(gameVM.SelectedGenreIds);

            // if filtered by genres - return gameList
            // if filtered by name - return gameList where game.Name.Contains(name)
            gameVM.Games = (gameVM.Name == null) ? gameList : gameList
                    .Where(g => g.Name
                    .Contains(gameVM.Name, StringComparison.OrdinalIgnoreCase))
                    .ToList();

            var genres = await _service.GetGenresAsync();
            _service.InitializeGenresList(gameVM, genres);

            return View("ListGames", gameVM);
        }
    }
}

GameStoreWeb/Controllers/UserController.cs
using GameStoreData.Identity.Data;
using GameStoreData.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace GameStoreWeb.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public UserController(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult ElevateUsers()
        {
            var users = _userManager.Users.ToList();
            return View(users);
        }

        public async Task<IActionResult> ElevateUserToAdmin(string username)
        {
            var user = _userManager.Users.FirstOrDefault(u => u.UserName == username);
            var roles = await _userManager.GetRolesAsync(user);

            await _userManager.RemoveFromRolesAsync(user, roles);
            await _userManager.AddToRoleAsync(user, "Admin");

            return RedirectToAction("ListGames", "Game");
        }

        public async Task<IActionResult> ElevateUserToManager(string username)
        {
            var user = _userManager.Users.FirstOrDefault(u => u.UserName == username);
            var roles = await _userManager.GetRolesAsync(user);

            await _userManager.RemoveFromRolesAsync(user, roles);
            await _userManager.AddToRoleAsync(user, "Manager");

            return RedirectToAction("ListGames", "Game");
        }
    }
}

GameStoreWeb/Views/Shared/ElevateUsers.cshtml
@using GameStoreData.Identity.Data;
@using Microsoft.AspNetCore.Identity;

@model IEnumerable<GameStoreData.Identity.Data.ApplicationUser>
@inject UserManager<ApplicationUser> UserManager

<div>
    @foreach (var user in Model.Where(u => !UserManager.GetRolesAsync(u).Result.Contains("Admin")))
    {
        <div class="games-list">
            <img src="@user.ImageURL" style="height:200px;width:200px" alt="image" onclick="imgClick(@user.Id)">
            <p class="details" style="font-weight:bold;width:200px">@(user.UserName)</p>
            <p class="details" style="font-weight:bold;width:200px">@(String.Join("/", UserManager.GetRolesAsync(user).Result))</p>
            <div style="margin-top:15px;width:200px;margin-left:25px;">
                @if (!UserManager.GetRolesAsync(user).Result.Contains("Manager"))
                {
                    <a class="button" asp-controller="User" asp-action="ElevateUserToManager" asp-route-username="@user.UserName">Elevate to Manager</a>
                }
                <a class="button" asp-controller="User" asp-action="ElevateUserToAdmin" asp-route-username="@user.UserName">Elevate to Admin</a>
            </div>
        </div>
    }
</div>

GameStoreWeb/Views/Shared/_CommentsPartial.cshtml
@using GameStoreData.Identity.Data;
@using GameStoreData.Service;
@using Microsoft.AspNetCore.Identity;
@using GameStoreData.Models;

@inject UserManager<ApplicationUser> UserManager
@inject SignInManager<ApplicationUser> SignInManager
@inject IGameService GameService

@model GameStoreData.ViewModels.CommentVM

@{
    int margin = 10;
    async Task RenderComments(Comment comment, string leftMargin = "10px")
    {
        if (!comment.IsActive) {
            <a asp-controller="Comment" id="restore-btn" style="margin-bottom:7px;" asp-action="ChangeCommentState" asp-route-id="@comment.Id">Restore</a>
        }
        else 
        {
            <dd id="comment" class="col-sm-10 comment" style="margin-left:@leftMargin; margin-bottom:8px;">
                <p class="user_comment">
                    @(comment.UserId != null ? UserManager.FindByIdAsync(comment.UserId).Result.UserName : "Guest")
                    <h10 style="font-weight:bold">@comment.TimeLeft</h10>
                </p>
                <h5>@comment.Body</h5>

                <div style="margin-bottom:15px;">
                    <a asp-controller="Comment" asp-action="ReplyToComment" asp-route-id="@comment.Id">Reply</a>

                    @if ((!SignInManager.IsSignedIn(User) && comment.UserId == null)
                    || SignInManager.IsSignedIn(User) && (UserManager.FindByIdAsync(comment.UserId).Result == UserManager.GetUserAsync(User).Result
                    || UserManager.GetRolesAsync(UserManager.GetUserAsync(User).Result).Result.Contains("Manager")))
                    {
                        <a asp-controller="Comment" asp-action="UpdateComment" asp-route-id="@comment.Id">Edit</a>
                        <a asp-controller="Comment" asp-action="ChangeCommentState" asp-route-id="@comment.Id">Delete</a>
                    }
                </div>
            </dd>

            if (comment.ChildComments != null)
            {
                margin += 35;
                foreach (var child in comment.ChildComments)
                {
                    await RenderComments(child, $"{margin}px");
                }
                margin -= 35;
            }
        }
    }
}

<hr />
<div>
    <dl class="row">
        @foreach (var comment in Model.GameComments)
        {
            if (comment.ParentCommentId == null)
            {
                await RenderComments(comment);
            }
        }
    </dl>
</div>

<div class="row">
    <div class="col-md-4">
        <form asp-action="AddComment" asp-controller="Comment" asp-route-model="@Model">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                Comment
                <input asp-for="Body" class="form-control" id="textfield" />
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="button" />
            </div>
            <input type="hidden" asp-for="@Model.CommentVMId" />
            <input type="hidden" asp-for="@Model.GameId" />
            <input type="hidden" asp-for="@Model.ParentCommentId" />
        </form>
    </div>
</div>

GameStoreWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GameStoreWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GameStoreWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Game" asp-action="ListGames">Game Store 🎮</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="ListGames">Game</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Index">Community</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Index">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Index">Support</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GameStoreWeb - <a asp-area="" asp-controller="Game" asp-action="Index">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>