GameStoreWeb/Controllers/GameController.cs
using GameStoreData.Models;
using GameStoreData.Service;
using GameStoreData.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace GameStoreWeb.Controllers
{
    public class GameController : Controller
    {
        private readonly IGameService _service;

        public GameController(IGameService service)
        {
            _service = service;
        }

        public IActionResult Index()
        {
            return RedirectToAction("ListGames");
        }

        [HttpGet("Create")]
        [Authorize(Roles = "Admin, Manager")]
        public async Task<IActionResult> Create()
        {
            var game = new Game();
            var gameVM = await _service.CreateGameVMAsync(game);

            return View(gameVM);
        }

        [HttpPost("Create")]
        public async Task<IActionResult> Create(GameVM gameVM)
        {
            var game = await _service.CreateGameAsync(gameVM);
            await _service.CreateNewGameAsync(game);

            return RedirectToAction("ListGames");
        }

        [HttpGet("Games")]
        public async Task<IActionResult> ListGames()
        {
            var gameVM = new GameVM();
            gameVM.Games = await _service.GetGamesAsync();

            var genres = await _service.GetGenresAsync();
            _service.InitializeGenresList(gameVM, genres);
            gameVM.SelectedGenreIds = genres.Select(g => g.Id).ToList();

            return View(gameVM);
        }

        [HttpGet("Update/{id}")]
        [Authorize(Roles = "Admin, Manager")]
        public async Task<IActionResult> Edit(int id)
        {
            var game = await _service.GetGameByIdAsync(id);
            var gameVM = await _service.CreateGameVMAsync(game);

            return View(gameVM);
        }

        [HttpPost]
        public async Task<IActionResult> Update(GameVM gameVM)
        {
            var game = await _service.CreateGameAsync(gameVM);
            await _service.UpdateGameAsync(game);

            return RedirectToAction("ListGames");
        }

        [Authorize(Roles = "Admin, Manager")]
        public async Task<IActionResult> Delete(int id)
        {
            await _service.DeleteGameAsync(id);
            return RedirectToAction("ListGames");
        }

        [HttpGet("Details/{id}")]
        public async Task<IActionResult> Details(int id)
        {
            TempData.TryGetValue("IsRedirected", out var isRedirected);
            var game = await _service.GetGameAndDeleteInactiveComments((bool?)isRedirected ?? false, id);
            TempData["IsRedirected"] = false;

            return View(game);
        }

        public async Task<IActionResult> FilterGames(GameVM gameVM)
        {
            var gameList = await _service.GetGamesWithSelectedGenresAsync(gameVM.SelectedGenreIds);

            // if filtered by genres - return gameList
            // if filtered by name - return gameList where game.Name.Contains(name)
            gameVM.Games = (gameVM.Name == null) ? gameList : gameList
                    .Where(g => g.Name
                    .Contains(gameVM.Name, StringComparison.OrdinalIgnoreCase))
                    .ToList();

            var genres = await _service.GetGenresAsync();
            _service.InitializeGenresList(gameVM, genres);

            return View("ListGames", gameVM);
        }
    }
}

GameStoreWeb/Views/Game/Create.cshtml
@model GameStoreData.ViewModels.GameVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create New Game</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Genres)
                <div class="col-sm-6">
                    @Html.ListBoxFor(model => model.SelectedGenreIds, Model.GenresList)
                </div>
            </div>

            <div class="form-group">@*there*@
                <input type="submit" value="Create" class="button" />
                <a asp-action="Index" class="button">Cancel</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GameStoreWeb/Views/Game/Details.cshtml
@using GameStoreData.Identity.Data;
@using GameStoreData.Service;
@using Microsoft.AspNetCore.Identity;

@inject UserManager<ApplicationUser> UserManager
@inject SignInManager<ApplicationUser> SignInManager
@inject IGameService GameService

@model GameStoreData.Models.Game

@{
    ViewData["Title"] = "GetGame";
}

<h1>@Model.Name</h1>
<hr />

<div>
    <dl class="row">
        <dd class="col-sm-3">
            <img src="@Model.Image" alt="image" height="100" width="100">
        </dd>

        <dd class="col-sm-3" style="text-align:center">
            <br /><br /><br />
            <h3 style="font-size:30px;">@(String.Join("/", Model.Genres.Select(g => g.Name)))</h3>
            <h3 style="font-size:30px;"> $@Html.DisplayFor(model => model.Price)</h3>
            <br /><br />
            <div>
                @if (SignInManager.IsSignedIn(User))
                {
                    @if (!UserManager.GetRolesAsync(UserManager
                    .GetUserAsync(User).Result).Result.Contains("User"))
                    {
                        <a asp-action="Edit" asp-route-id="@Model?.Id" class="button">Update</a>
                    }
                    <a asp-controller="CartItem" asp-action="AddGameToCart" asp-route-id="@Model?.Id" class="buygame">Add to Cart</a>
                }
                else
                {
                    <a asp-controller="CartItem" asp-action="BuyGames" asp-route-id="@Model?.Id" class="buygame">Buy</a>
                }
                <a asp-action="Index" asp-controller="Game" class="button">Go Back</a>
            </div>
        </dd>
    </dl>
</div>

@{
    <partial name="_CommentsPartial" model="@Model?.CommentVM" />
}

GameStoreWeb/Views/Game/Edit.cshtml
@using Newtonsoft.Json;
@model GameStoreData.ViewModels.GameVM

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Game</h1>

<hr />  
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                @Html.LabelFor(model => model.Genres)
                <div class="col-sm-6">
                    @Html.ListBoxFor(model => model.SelectedGenreIds, Model.GenresList)
                </div>
            </div>

            <div>
                <input type="submit" value="Save" class="button" />
                <a asp-action="Index" class="button">Cancel</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GameStoreWeb/Views/Game/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

GameStoreWeb/Views/Game/ListGames.cshtml
@using GameStoreData.Identity.Data;
@using Microsoft.AspNetCore.Identity;

@model GameStoreData.ViewModels.GameVM

@inject UserManager<ApplicationUser> UserManager
@inject SignInManager<ApplicationUser> SignInManager

@{
    bool hideChangeBtns = true;
    ViewData["Title"] = "ListGames";
}

<div>
    <a class="button" onclick="handleFilterBtn()">By Genres</a>
    <a class="button" onclick="handleFilterByNameBtn()">By Name</a>

    <form asp-action="FilterGames">
        <div class="form-group" id="filtergames" style="display:none">
            <div class="col-sm-6 select">
                @Html.ListBoxFor(model => model.SelectedGenreIds, Model.GenresList)
            </div>
        </div>

        <div class="form-group" id="filterbyname" style="display:none">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" />
        </div>

        <div class="form-group">
            <input type="submit" value="Filter" class="button" />
        </div>
    </form>
</div>

<div style="text-align:center; margin-bottom:20px;">
    @if (SignInManager.IsSignedIn(User) && !UserManager.GetRolesAsync(UserManager
        .GetUserAsync(User).Result).Result.Contains("User"))
    {
        hideChangeBtns = false;
        <a class="button" asp-action="Create">New Game</a>
    }
</div>

<div>
    @foreach (var item in Model.Games)
    {
        <div class="games-list">
            <img src="@item.Image" alt="image" onclick="imgClick(@item.Id)">
            <p class="details">
                @{ string s = String.Join("/", item.Genres.Select(g => g.Name)); }
                @(string.IsNullOrEmpty(s) ? "No Genre" : s)
                <br>@(item.Name)
            </p>
            <p class="details" style="font-weight:bold">$@(item.Price)</p>
            <div style="margin-top:15px; text-align:center;">
                @if(SignInManager.IsSignedIn(User))
                {
                    <a class="buygame" asp-controller="CartItem" asp-action="AddGameToCart" asp-route-id="@item.Id">Add</a>
                    @if (!hideChangeBtns)
                    {
                        <a class="button" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                        <a class="button" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    }
                }
                else
                {
                    <a class="buygame" asp-controller="CartItem" asp-action="BuyGames" asp-route-id="@item.Id">Buy</a>
                }
            </div>
        </div>
    }
</div>

<div class="row" style="clear:both"></div>